### ISSUE TITLE
Cant find modules ending with '.jsx' or '.es6' file extensions

### ISSUE THREAD

**Issue by jennasalau** [arian/partition-bundle#10]
It would be really good if we can define extensions for files to be considered as modules. Such as `.jsx` or `.es6`. 

I refer to the `--extension` option under advanced options in the [browserify readme](https://github.com/substack/node-browserify#usage) that I'm utilising. 

So for instance in our map json file, I want to load a React jsx module;

This works:

``` json
{
    "feed-bundle.js": [
      "./modules/Feed.jsx"
    ]
}
```

But this doesn't (no extension defined). This name is preferred as it's the default alias.

``` json
{
    "feed-bundle.js": [
      "./modules/Feed"
    ]
}
```

Produces error:
`Warning: Cannot find module './modules/Feed' from '/source/app' Use --force to continue.`

**Comment by arian** [comment]
Hi @jennasalau, version 2.1.0 should fix your problem.

**Comment by jennasalau** [comment]
Thank you :))
