### ISSUE TITLE
Behavior regarding 'require' isn't clearly documented

### ISSUE THREAD

**Issue by ggazzi** [arian/partition-bundle#15]
Today I spent some time trying to bundle some libraries separately from the main module in order to blackbox them for debugging. It took me a while to realize that partition-bundle couldn't put them in a separate bundle because they were `require`d  from the main module.

While it should be relatively obvious that partition-bundle won't replace a call to `require` with a call to `loadjs` (which would be non-trivial), the implications of this to the bundling may not be so obvious. Therefore it might be useful to have a section on the readme stating explicitly where the `require`d modules are placed, especially if they are needed in multiple bundles. Emphasizing that this will override the map file would also be useful.

**Comment by Scarysize** [comment]
Thanks a lot for this issue. I spent hours(!) trying to figure out why my seperate bundle file stayed empty...
I will try to submit a PR to update the README, hopefully saving future users some time.

**Comment by Scarysize** [comment]
@ggazzi With the merge, this can be closed.
