### ISSUE TITLE
wildcards

### ISSUE THREAD

**Issue by benmonro** [arian/partition-bundle#2]
is there anyway to use wildcards in the mapping instead of having to list each individual file?

**Comment by arian** [comment]
You only need to list the entry points.

So if you list `a.js` and `b.js`, and `a` depends on `c` and `e`, `c` and `e` will automatically be in the same file as `a`. The same holds for dependencies of `b`.

If `a` and `b` both depend on `f`, `f` will usually be in the _main_ file.
