### ISSUE TITLE
Partition file contains module which map file says belongs elsewhere

### ISSUE THREAD

**Issue by shaine** [arian/partition-bundle#4]
I'm encountering an issue with a large application where the map file explicitly lists a module as belonging to the second partition, but it's getting included in the last defined partition because a deeply nested dependency requires it. For example:

```
{
    "core.js": [
        "./src/index"
    ],
    "post-core.js": [
        "./src/core/models/user",
        "./src/message/controller"
    ],
    [...]
    "last.js": [
        "./src/button/controller"
    ]
}
```

states that `core/models/user` should go into `post-core.js`. `message/controller` does not reference `user`. Several requires deep inside of `button/controller`, `user` is also required. In my real app, `user` is getting defined inside of `last.js` in spite of the explicit ordering.

I've tried recreating this problem inside of an example project, but it seems to behave as expected there. I can't see any reason why my larger application is acting this way - If I comment out the deeply nested require in the last partition's modules, the problematic module does end up in the correct partition file. I'll keep trying to diagnose the problem, but I'm hoping someone else has some ideas on what either I'm doing wrong or where the bad logic in partition-bundle might be. Thanks!

**Comment by shaine** [comment]
Ah, okay, I found the comment in the source that explains it. It seems partition-bundle will put a module into whichever partition file whose dependency tree requires the module the most times, and the map file doesn't trump that decision. Expected behavior, for me anyway, would be that the first partition file that the map explicitly states a module belongs to (if specified), would be the partition that receives the module. Thoughts?

**Comment by arian** [comment]
I think you are right, hopefully 99eb79c fixes it for you. (in version 1.1.0).

**Comment by shaine** [comment]
Works great! Thank you for the fast update!
