### ISSUE TITLE
Doesn't play nice with loading npm modules

### ISSUE THREAD

**Issue by fkling** [arian/partition-bundle#9]
Lets say I have installed a module `foo` and have the following configuration:

``` json
{
    "entry.js": ["..."],
    "foo.js": ["foo"]
}
```

Then I'm not able to load the module via `loadjs(['foo'], ...)` because the mapping generated in `loadjs.map` looks something like

``` js
loadjs.map = {'./node_modules/foo/index': [1]}
```

So it seems like I have to use `loadjs(['./node_modules/foo/index'], ...)` instead, which is inconvenient.

As a workaround, I could create my own module which simply wraps `foo`, but I was wondering whether this could be fixed. There should be at least a notice that this doesn't work as expected.

**Comment by arian** [comment]
Hi @fkling, I think I just fixed it, let me know if it works for you as well!

**Comment by fkling** [comment]
I know it's a very late reply, but I just wanted to let you know that it works perfectly, thank you!
